name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag itshoney/ca3:latest
    - name: Push Docker image
      run: |
          docker tag itshoney/ca3:latest ${{ secrets.DOCKER_USERNAME }}/itshoney/ca3:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/itshoney/ca3:latest
